### ISSUE TITLE
Globals

### ISSUE THREAD

**Issue by TuriGuilano** [chelseadoeleman/web-app-from-scratch-18-19#9]
Try avoiding the global scope;

https://github.com/chelseadoeleman/web-app-from-scratch-18-19/blob/f042d40c9b7a6fdd43b954edf4cbdc9bc2258f9a/public/js/app.js#L3-L6

https://github.com/chelseadoeleman/web-app-from-scratch-18-19/blob/f042d40c9b7a6fdd43b954edf4cbdc9bc2258f9a/public/js/app.js#L11-L25

**Comment by chelseadoeleman** [comment]
Refactored everything out of the global scope
